# -*- coding: utf-8 -*-
"""sanskrit_RAG1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eiyI39aWQNR7mylhoFoaTTS-5KYlaJwX
"""

print("lets go")

"""Install Dependencies"""

!pip install -q langchain langchain-community langchain-text-splitters \
             langchain-huggingface sentence-transformers faiss-cpu \
             transformers pypdf accelerate

"""Upload Your Sanskrit Documents"""

from google.colab import files

print("Upload your .txt or .pdf Sanskrit documents")
uploaded = files.upload()

doc_files = list(uploaded.keys())
print(f"Uploaded: {doc_files}")

""" Load & Preprocess Documents"""

from langchain_community.document_loaders import TextLoader, PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter

docs = []

for fname in doc_files:
    if fname.endswith(".pdf"):
        loader = PyPDFLoader(fname)
    else:
        loader = TextLoader(fname, encoding="utf-8")
    docs.extend(loader.load())

print(f"Loaded {len(docs)} document(s)")

splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=50,
    separators=["।", "\n\n", "\n", " "]   # Sanskrit-aware separators
)
chunks = splitter.split_documents(docs)
print(f"Total chunks: {len(chunks)}")

"""Create Embeddings & FAISS Index"""

from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS

print("Loading embedding model (CPU)...")
embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2",
    model_kwargs={"device": "cpu"}
)

print("Building FAISS index...")
vectorstore = FAISS.from_documents(chunks, embeddings)
vectorstore.save_local("sanskrit_faiss_index")
print("✅ Index saved!")

""" Load CPU-based LLM"""

from transformers import pipeline

print("Loading LLM (this may take a minute)...")
llm_pipeline = pipeline(
    "text2text-generation",
    model="google/flan-t5-base",   # Swap for flan-t5-large for better quality
    device=-1                       # -1 = CPU
)
print("✅ LLM ready!")

"""Build the RAG Query Function"""

def retrieve_and_answer(query: str, top_k: int = 3):
    print(f"\n🔍 Query: {query}\n")

    # Step 1: Retrieve relevant chunks
    retriever = vectorstore.as_retriever(search_kwargs={"k": top_k})
    relevant_docs = retriever.invoke(query)

    # Step 2: Build context
    context = "\n\n".join([doc.page_content for doc in relevant_docs])
    print("📄 Retrieved Context:\n", context[:600], "...\n")

    # Step 3: Generate answer
    prompt = f"""Answer the question based on the Sanskrit text context below.

Context:
{context}

Question: {query}
Answer:"""

    result = llm_pipeline(prompt, max_new_tokens=200, truncation=True)
    answer = result[0]["generated_text"]

    print("💬 Answer:\n", answer)
    return answer

"""Run Queries"""

# English query
retrieve_and_answer("Who is Shankhanaada and what mistake did he make?")

# Story moral
retrieve_and_answer("What is the moral of the story about the devotee?")

# Transliterated Sanskrit query
retrieve_and_answer("What did kAlidAsa do when the foreign scholar arrived?")

print("🪷 Sanskrit RAG System Ready! Type 'quit' to exit.\n")

while True:
    query = input("Enter your query (Sanskrit / English / Transliterated): ")
    if query.lower() == "quit":
        break
    retrieve_and_answer(query)

